AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  qr_generator

  Sample SAM Template for qr_generator

Parameters:
  BucketName:
    Type: String
    Description: Name of bucket to dump QR codes to

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  QRGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: qr_generator/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          BUCKET: !Ref BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  QRGeneratorFunction:
    Description: "QR Generator Lambda Function ARN"
    Value: !GetAtt QRGeneratorFunction.Arn
  QRGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for QR generator function"
    Value: !GetAtt QRGeneratorFunctionRole.Arn
