version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "face-trainer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6r788aturf04"
s3_prefix = "face-trainer"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CollectionId=infosys-chester"

